// Generated by unRap v1.06 by Kegetys

class SU_33_BodyVortices : BodyVortices
{
	class BodyTrail1
	{
		simulation = "particles";
		type = "SU_33_BodyTrail";
		qualityLevel = 2;
		enabled = "accelY interpolate [79.9999999,80,-1,1]";
	};
	
	class BodyTrail1Med {
		simulation = "particles";
		type = "SU_33_BodyTrailMed";
		qualityLevel = 1;
		enabled = "accelY interpolate [79.9999999,80,-1,1]";
	};
};
