class CfgSkeletons
{
	class Default
	{
		isDiscrete = 1;
		skeletonInherit = "";
		skeletonBones[] = {};
	};
	class SACSu33Skeleton : Default
	{
	};
};
class CfgModels
{
	class Default
	{
		sections[] = {};
		sectionsInherit="";
		skeletonName = "SACSu33Skeleton";
	};
	class SACSu33S : Default
	{
		skeletonName="SACSu33Skeleton";
		sections[]=
		{
			"seat",
			"canopy",
			"canopyglass",
			"num2",
			"num1",
		};
		class Animations
		{
			class Flap_nr1
			{
				type="rotation";
				angle0=0;
				angle1=0.4;
				axis="flap_nr1_axis";
				memory=1;
				minValue=0.5;
				maxValue=1;
				minPhase=0.5;
				maxPhase=1;
				source="flap";
				sourceAddress=0;
				selection="flap_nr1";
			};
			class Flap_nl1
			{
				type="rotation";
				angle0=0;
				angle1=-0.4;
				axis="flap_nl1_axis";
				memory=1;
				minValue=0.5;
				maxValue=1;
				minPhase=0.5;
				maxPhase=1;
				source="flap";
				sourceAddress=0;
				selection="flap_nl1";
			};
			class Flap_nr2
			{
				type="rotation";
				angle0=0;
				angle1=0.4;
				axis="flap_nr1_axis";
				memory=1;
				minValue=0.5;
				maxValue=1;
				minPhase=0.5;
				maxPhase=1;
				source="flap";
				sourceAddress=0;
				selection="flap_nr2";
			};
			class Flap_nl2
			{
				type="rotation";
				angle0=0;
				angle1=-0.4;
				axis="flap_nl1_axis";
				memory=1;
				minValue=0.5;
				maxValue=1;
				minPhase=0.5;
				maxPhase=1;
				source="flap";
				sourceAddress=0;
				selection="flap_nl2";
			};
			class aileron_l1
			{
				type="rotation";
				angle0=0;
				angle1=-0.2;
				axis="aileron_l_axis";
				memory=1;
				minValue=0.5;
				maxValue=1;
				minPhase=0.5;
				maxPhase=1;
				source="flap";
				sourceAddress=0;
				selection="aileron_l1";
			};
			class aileron_r1
			{
				type="rotation";
				angle0=0;
				angle1=0.2;
				axis="aileron_r_axis";
				memory=1;
				minValue=0.5;
				maxValue=1;
				minPhase=0.5;
				maxPhase=1;
				source="flap";
				sourceAddress=0;
				selection="aileron_r1";
			};
			class Flap_r11
			{
				type="rotation";
				angle0=0;
				angle1=0.23;
				axis="flap_r11_axis";
				memory=1;
				minValue=0;
				maxValue=0.5;
				minPhase=0;
				maxPhase=0.5;
				source="flap";
				sourceAddress=0;
				selection="flap_r11";
			};
			class Flap_l11
			{
				type="rotation";
				angle0=0;
				angle1=-0.23;
				axis="flap_l11_axis";
				memory=1;
				minValue=0;
				maxValue=0.5;
				minPhase=0;
				maxPhase=0.5;
				source="flap";
				sourceAddress=0;
				selection="flap_l11";
			};
			class Flap_r12
			{
				type="rotation";
				angle0=0;
				angle1=0.3;
				axis="flap_r12_axis";
				memory=1;
				minValue=0.5;
				maxValue=1;
				minPhase=0.5;
				maxPhase=1;
				source="flap";
				sourceAddress=0;
				selection="flap_r12";
			};
			class Flap_l12
			{
				type="rotation";
				angle0=0;
				angle1=-0.3;
				axis="flap_l12_axis";
				memory=1;
				minValue=0.5;
				maxValue=1;
				minPhase=0.5;
				maxPhase=1;
				source="flap";
				sourceAddress=0;
				selection="flap_l12";
			};
			class Flap_r21
			{
				type="rotation";
				angle0=0;
				angle1=-0.23;
				axis="flap_r11_axis";
				memory=1;
				minValue=0;
				maxValue=0.5;
				minPhase=0;
				maxPhase=0.5;
				source="flap";
				sourceAddress=0;
				selection="flap_r21";
			};
			class Flap_l21
			{
				type="rotation";
				angle0=0;
				angle1=0.23;
				axis="flap_l11_axis";
				memory=1;
				minValue=0;
				maxValue=0.5;
				minPhase=0;
				maxPhase=0.5;
				source="flap";
				sourceAddress=0;
				selection="flap_l21";
			};
			class Flap_r22
			{
				type="rotation";
				angle0=0;
				angle1=-0.3;
				axis="flap_r12_axis";
				memory=1;
				minValue=0.5;
				maxValue=1;
				minPhase=0.5;
				maxPhase=1;
				source="flap";
				sourceAddress=0;
				selection="flap_r22";
			};
			class Flap_l22
			{
				type="rotation";
				angle0=0;
				angle1=0.3;
				axis="flap_l12_axis";
				memory=1;
				minValue=0.5;
				maxValue=1;
				minPhase=0.5;
				maxPhase=1;
				source="flap";
				sourceAddress=0;
				selection="flap_l22";
			};
			class aileron_l
			{
				type="rotation";
				angle0=-0.4;
				angle1=0.4;
				axis="aileron_l_axis";
				memory=1;
				minValue=-1;
				maxValue=1;
				minPhase=-1;
				maxPhase=1;
				source="aileron";
				sourceAddress=0;
				selection="aileron_l";
			};
			class aileron_r
			{
				type="rotation";
				angle0=-0.4;
				angle1=0.4;
				axis="aileron_r_axis";
				memory=1;
				minValue=-1;
				maxValue=1;
				minPhase=-1;
				maxPhase=1;
				source="aileron";
				sourceAddress=0;
				selection="aileron_r";
			};
			class elevator_ll
			{
				type="rotation";
				angle0=-0.25;
				angle1=0.25;
				axis="elevator_rr_axis";
				memory=1;
				minValue=-1;
				maxValue=1;
				minPhase=-1;
				maxPhase=1;
				source="aileron";
				sourceAddress=0;
				selection="elevator_ll";
			};
			class elevator_rr
			{
				type="rotation";
				angle0=0.25;
				angle1=-0.25;
				axis="elevator_rr_axis";
				memory=1;
				minValue=-1;
				maxValue=1;
				minPhase=-1;
				maxPhase=1;
				source="aileron";
				sourceAddress=0;
				selection="elevator_rr";
			};
			class elevator_l
			{
				type="rotation";
				angle0=0.35;
				angle1=-0.35;
				axis="elevator_rr_axis";
				memory=1;
				minValue=-1;
				maxValue=1;
				minPhase=-1;
				maxPhase=1;
				source="elevator";
				sourceAddress=0;
				selection="elevator_l";
			};
			class elevator_r
			{
				type="rotation";
				angle0=0.35;
				angle1=-0.35;
				axis="elevator_rr_axis";
				memory=1;
				minValue=-1;
				maxValue=1;
				minPhase=-1;
				maxPhase=1;
				source="elevator";
				sourceAddress=0;
				selection="elevator_r";
			};
			class canard
			{
				type="rotation";
				angle0=-0.499164;
				angle1=0.499164;
				axis="canard_axis";
				memory=1;
				minValue=-1;
				maxValue=1;
				minPhase=-1;
				maxPhase=1;
				source="elevator";
				sourceAddress=0;
				selection="canard";
			};
			class RudderL
			{
				type="rotation";
				angle0=-0.375246;
				angle1=0.375246;
				axis="rudder_l_axis";
				memory=1;
				minValue=-1;
				maxValue=1;
				minPhase=-1;
				maxPhase=1;
				source="rudder";
				sourceAddress=0;
				selection="rudder_l";
			};
			class RudderR
			{
				type="rotation";
				angle0=-0.375246;
				angle1=0.375246;
				axis="rudder_r_axis";
				memory=1;
				minValue=-1;
				maxValue=1;
				minPhase=-1;
				maxPhase=1;
				source="rudder";
				sourceAddress=0;
				selection="rudder_r";
			};
			class canopy
			{
				type="rotation";
				angle0=-0.5235988;
				angle1=0;
				axis="canopy_axis";
				memory=1;
				minValue=0;
				maxValue=8;
				minPhase=0;
				maxPhase=8;
				source="cabin";
				sourceAddress=0;
				selection="canopy";
			};
			class canopy_piston
			{
				type="rotation";
				angle0=0.6981317;
				angle1=0;
				axis="canopy_piston_axis";
				memory=1;
				minValue=4;
				maxValue=8;
				minPhase=4;
				maxPhase=8;
				source="cabin";
				sourceAddress=0;
				selection="canopy_piston";
			};
			class canopy_piston2
			{
				type="translation";
				offset0=0.2;
				offset1=-0.2;
				axis="canopy_piston2_axis";
				memory=1;
				minValue=0;
				maxValue=4;
				minPhase=0;
				maxPhase=4;
				source="cabin";
				sourceAddress=0;
				selection="canopy_piston2";
			};
			class wing
			{
				type="rotation";
				angle0=0;
				angle1=0.1;
				axis="";	//unknown :(
				memory=0;
				minValue=0;
				maxValue=1;
				minPhase=0;
				maxPhase=1;
				source="user";
				sourceAddress=0;
				selection="wing";
			};
			class wing_l
			{
				type="rotation";
				angle0=0;
				angle1=-2.094395;
				axis="wing_l_axis";
				memory=1;
				minValue=0;
				maxValue=1;
				minPhase=0;
				maxPhase=1;
				source="user";
				sourceAddress=0;
				selection="wing_l";
			};
			class wing_r
			{
				type="rotation";
				angle0=0;
				angle1=2.094395;
				axis="wing_r_axis";
				memory=1;
				minValue=0;
				maxValue=1;
				minPhase=0;
				maxPhase=1;
				source="user";
				sourceAddress=0;
				selection="wing_r";
			};
			class elevator_r1
			{
				type="rotation";
				angle0=0;
				angle1=-1.570796;
				axis="elevator_r1_axis";
				memory=1;
				minValue=0;
				maxValue=1;
				minPhase=0;
				maxPhase=1;
				source="user";
				sourceAddress=0;
				selection="elevator_r1";
			};
			class elevator_l1
			{
				type="rotation";
				angle0=0;
				angle1=1.570796;
				axis="elevator_l1_axis";
				memory=1;
				minValue=0;
				maxValue=1;
				minPhase=0;
				maxPhase=1;
				source="user";
				sourceAddress=0;
				selection="elevator_l1";
			};
			class airbrake
			{
				type="rotation";
				angle0=0;
				angle1=0.7504916;
				axis="airbrake_axis";
				memory=1;
				minValue=0;
				maxValue=1;
				minPhase=0;
				maxPhase=1;
				source="SpeedBrake";
				sourceAddress=0;
				selection="airbrake";
			};
			class airbrake_1
			{
				type="rotation";
				angle0=-0.03490658;
				angle1=-0.418879;
				axis="airbrake_1_axis";
				memory=1;
				minValue=0;
				maxValue=0.95;
				minPhase=0;
				maxPhase=0.95;
				source="SpeedBrake";
				sourceAddress=0;
				selection="airbrake_1";
			};
			class airbrake_2
			{
				type="translation";
				offset0=-0.05;
				offset1=-0.57;
				axis="door_br2_axis";
				memory=1;
				minValue=0;
				maxValue=1;
				minPhase=0;
				maxPhase=1;
				source="SpeedBrake";
				sourceAddress=0;
				selection="airbrake_2";
			};
			class gear_n
			{
				type="rotation";
				angle0=0;
				angle1=-1.692969;
				axis="gear_n_axis";
				memory=1;
				minValue=0;
				maxValue=0.6;
				minPhase=0;
				maxPhase=0.6;
				source="Gear";
				sourceAddress=0;
				selection="gear_n";
			};
			class gear_n_Steering
			{
				type="rotation";
				angle0=-0.349066;
				angle1=0.349066;
				axis="gear_n_steering_axis";
				memory=1;
				minValue=-1;
				maxValue=1;
				minPhase=-1;
				maxPhase=1;
				source="noseWheelTurn";
				sourceAddress=0;
				selection="gear_n_steering";
			};
			class door_n
			{
				type="rotation";
				angle0=-1.570796;
				angle1=0;
				axis="door_n_axis";
				memory=1;
				minValue=0.5;
				maxValue=1;
				minPhase=0.5;
				maxPhase=1;
				source="Gear";
				sourceAddress=0;
				selection="door_n";
			};
			class hook
			{
				type="rotation";
				angle0=0;
				angle1=0.7504916;
				axis="hook_axis";
				memory=1;
				minValue=0;
				maxValue=1;
				minPhase=0;
				maxPhase=1;
				source="user";
				sourceAddress=0;
				selection="hook";
			};
			class gear_n_piston_2
			{
				type="rotation";
				angle0=0.5235988;
				angle1=0;
				axis="gear_n_piston_2_axis";
				memory=1;
				minValue=0;
				maxValue=0.55;
				minPhase=0;
				maxPhase=0.55;
				source="Gear";
				sourceAddress=0;
				selection="gear_n_piston_2";
			};
			class gear_r1
			{
				type="rotation";
				angle0=0;
				angle1=-1.919862;
				axis="gear_r_axis";
				memory=1;
				minValue=0;
				maxValue=0.54;
				minPhase=0;
				maxPhase=0.54;
				source="Gear";
				sourceAddress=0;
				selection="gear_r1";
			};
			class gear_r
			{
				type="rotation";
				angle0=0;
				angle1=-1.413717;
				axis="gear_r_axis";
				memory=1;
				minValue=0;
				maxValue=0.48;
				minPhase=0;
				maxPhase=0.48;
				source="Gear";
				sourceAddress=0;
				selection="gear_r";
			};
			class door_br1
			{
				type="rotation";
				angle0=2.007129;
				angle1=0;
				axis="door_br1_axis";
				memory=1;
				minValue=0.54;
				maxValue=1;
				minPhase=0.54;
				maxPhase=1;
				source="Gear";
				sourceAddress=0;
				selection="door_br1";
			};
			class door_br2
			{
				type="rotation";
				angle0=-1.658063;
				angle1=0;
				axis="door_br2_axis";
				memory=1;
				minValue=0.54;
				maxValue=1;
				minPhase=0.54;
				maxPhase=1;
				source="Gear";
				sourceAddress=0;
				selection="door_br2";
			};
			class gear_r_pick
			{
				type="rotation";
				angle0=0;
				angle1=1.570796;
				axis="gear_r_pick_axis";
				memory=1;
				minValue=0.1;
				maxValue=0.3;
				minPhase=0.1;
				maxPhase=0.3;
				source="Gear";
				sourceAddress=0;
				selection="gear_r_pick";
			};
			class gear_l1
			{
				type="rotation";
				angle0=0;
				angle1=1.919862;
				axis="gear_l_axis";
				memory=1;
				minValue=0;
				maxValue=0.54;
				minPhase=0;
				maxPhase=0.54;
				source="Gear";
				sourceAddress=0;
				selection="gear_l1";
			};
			class gear_l
			{
				type="rotation";
				angle0=0;
				angle1=-1.413717;
				axis="gear_l_axis";
				memory=1;
				minValue=0;
				maxValue=0.48;
				minPhase=0;
				maxPhase=0.48;
				source="Gear";
				sourceAddress=0;
				selection="gear_l";
			};
			class door_bl1
			{
				type="rotation";
				angle0=-2.007129;
				angle1=0;
				axis="door_bl1_axis";
				memory=1;
				minValue=0.54;
				maxValue=1;
				minPhase=0.54;
				maxPhase=1;
				source="Gear";
				sourceAddress=0;
				selection="door_bl1";
			};
			class door_bl2
			{
				type="rotation";
				angle0=1.658063;
				angle1=0;
				axis="door_bl2_axis";
				memory=1;
				minValue=0.54;
				maxValue=1;
				minPhase=0.54;
				maxPhase=1;
				source="Gear";
				sourceAddress=0;
				selection="door_bl2";
			};
			class gear_l_pick
			{
				type="rotation";
				angle0=0;
				angle1=-1.570796;
				axis="gear_l_pick_axis";
				memory=1;
				minValue=0.1;
				maxValue=0.3;
				minPhase=0.1;
				maxPhase=0.3;
				source="Gear";
				sourceAddress=0;
				selection="gear_l_pick";
			};
			class Ladder
			{
				type="hide";
				hideValue=0.1;
				minValue=7.49;
				maxValue=7.5;
				minPhase=7.49;
				maxPhase=7.5;
				source="cabin";
				sourceAddress=0;
				selection="ladder";
			};
			class Wheel_n
			{
				type="rotationX";
				angle0=0;
				angle1=-3.141593;
				axis="wheel_n_axis";
				memory=1;
				minValue=0;
				maxValue=1;
				minPhase=0;
				maxPhase=1;
				source="wheel";
				sourceAddress=1;
				selection="wheel_n";
			};
			class Wheel_r
			{
				type="rotationX";
				angle0=0;
				angle1=-3.141593;
				axis="wheel_r_axis";
				memory=1;
				minValue=0;
				maxValue=1;
				minPhase=0;
				maxPhase=1;
				source="wheel";
				sourceAddress=1;
				selection="wheel_r";
			};
			class Wheel_l
			{
				type="rotationX";
				angle0=0;
				angle1=-3.141593;
				axis="wheel_l_axis";
				memory=1;
				minValue=0;
				maxValue=1;
				minPhase=0;
				maxPhase=1;
				source="wheel";
				sourceAddress=1;
				selection="wheel_l";
			};
			class nozzle1
			{
				type="translation";
				offset0=0.1;
				offset1=-0.1;
				axis="gear_l1_axis";
				memory=1;
				minValue=0;
				maxValue=1;
				minPhase=0;
				maxPhase=1;
				source="rpm";
				sourceAddress=0;
				selection="nozzle1";
			};
			class nozzle2
			{
				type="translation";
				offset0=0.1;
				offset1=-0.1;
				axis="nozzle2_axis";
				memory=1;
				minValue=0;
				maxValue=1;
				minPhase=0;
				maxPhase=1;
				source="rpm";
				sourceAddress=0;
				selection="nozzle2";
			};
			class nozzle3
			{
				type="translation";
				offset0=0.1;
				offset1=-0.1;
				axis="canopy_axis";
				memory=1;
				minValue=0;
				maxValue=1;
				minPhase=0;
				maxPhase=1;
				source="rpm";
				sourceAddress=0;
				selection="nozzle3";
			};
			class nozzle4
			{
				type="translation";
				offset0=0.1;
				offset1=-0.1;
				axis="nozzle4_axis";
				memory=1;
				minValue=0;
				maxValue=1;
				minPhase=0;
				maxPhase=1;
				source="rpm";
				sourceAddress=0;
				selection="nozzle4";
			};
			class nozzle5
			{
				type="translation";
				offset0=-0.1;
				offset1=0.1;
				axis="gear_l1_axis";
				memory=1;
				minValue=0;
				maxValue=1;
				minPhase=0;
				maxPhase=1;
				source="rpm";
				sourceAddress=0;
				selection="nozzle5";
			};
			class nozzle6
			{
				type="translation";
				offset0=-0.1;
				offset1=0.1;
				axis="nozzle2_axis";
				memory=1;
				minValue=0;
				maxValue=1;
				minPhase=0;
				maxPhase=1;
				source="rpm";
				sourceAddress=0;
				selection="nozzle6";
			};
			class nozzle7
			{
				type="translation";
				offset0=-0.1;
				offset1=0.1;
				axis="canopy_axis";
				memory=1;
				minValue=0;
				maxValue=1;
				minPhase=0;
				maxPhase=1;
				source="rpm";
				sourceAddress=0;
				selection="nozzle7";
			};
			class nozzle8
			{
				type="translation";
				offset0=-0.1;
				offset1=0.1;
				axis="nozzle4_axis";
				memory=1;
				minValue=0;
				maxValue=1;
				minPhase=0;
				maxPhase=1;
				source="rpm";
				sourceAddress=0;
				selection="nozzle8";
			};
			class ABcut
			{
				type="rotation";
				angle0=0;
				angle1=0.1;
				axis="";	//unknown :(
				memory=0;
				minValue=0;
				maxValue=1;
				minPhase=0;
				maxPhase=1;
				source="user";
				sourceAddress=0;
				selection="abcut";
			};
		};
	};
};
