// Generated by unRap v1.06 by Kegetys
/*
class CfgAmmo {
	class B_30mm_HE;	// External class reference

	class SAC_B_30mm_HE : B_30mm_HE {
		hit = 80;
		indirectHit = 50;
		indirectHitRange = 0.8;
		model = "\a3\weapons_f\Data\bullettracer\tracer_yellow";
		muzzleEffect = "";
	};
	class R_S8T_AT;	// External class reference

	class SAC_R_S8T_AT : R_S8T_AT {
		model = "\a3\air_f\70mmRocket";
		hit = 430;
		indirectHit = 60;
		indirectHitRange = 7;
		cost = 200;
		maxSpeed = 1600;
		thrustTime = 0.2;
		thrust = 3000;
		sideAirFriction = 0.2;
	};

	class SAC_R_S8T_HE : SAC_R_S8T_AT {
		model = "\a3\air_f\70mmRocket";
		hit = 180;
		indirectHit = 20;
		indirectHitRange = 11;
		cost = 200;
		maxSpeed = 1600;
		thrustTime = 0.2;
		thrust = 3000;
		sideAirFriction = 0.2;
	};
	class M_R73_AA;	// External class reference

	class SAC_M_R73_AA : M_R73_AA {
		model = "\ca\air3\su34\r73_fly";
		hit = 60;
		indirectHit = 30;
		indirectHitRange = 7;
		maneuvrability = 40;
		simulationStep = 0.002;
		trackOversteer = 5.0;
		trackLead = 0.4;
		airLock = 1;
		irLock = 1;
		thrustTime = 10;
		thrust = 350;
		cost = 10000;
		maxSpeed = 2000;
	};

	class SAC_M_R27RE : SAC_M_R73_AA {
		model = "\SACSu33\SACR27RE.p3d";
		proxyShape = "\SACSu33\SACR27RE_proxy.p3d";
		hit = 100;
		indirectHit = 50;
		indirectHitRange = 9;
		maneuvrability = 20;
		simulationStep = 0.002;
		trackOversteer = 5.0;
		trackLead = 0.95;
		airLock = 1;
		irLock = 1;
		initTime = 0.3;
		thrustTime = 15;
		thrust = 400;
		cost = 10000;
		maxSpeed = 2300;
		minRange = 300;
		minRangeProbab = 0.1;
		midRange = 2000;
		midRangeProbab = 0.9;
		maxRange = 5000;
		maxRangeProbab = 0.7;
		effectsMissile = "SACmissile1";
	};

	class SAC_M_R77 : SAC_M_R73_AA {
		model = "\SACSu33\SACR77.p3d";
		proxyShape = "\SACSu33\SACR77_proxy.p3d";
		hit = 80;
		indirectHit = 40;
		indirectHitRange = 9;
		maneuvrability = 30;
		simulationStep = 0.002;
		trackOversteer = 5.0;
		trackLead = 0.7;
		airLock = 1;
		irLock = 1;
		thrustTime = 12;
		thrust = 380;
		cost = 10000;
		initTime = 0.15;
		maxSpeed = 2100;
		minRange = 100;
		minRangeProbab = 0.1;
		midRange = 1800;
		midRangeProbab = 0.9;
		maxRange = 6000;
		maxRangeProbab = 0.7;
		effectsMissile = "SACmissile1";
	};
	class Bo_FAB_250;	// External class reference

	class SAC_FAB250 : Bo_FAB_250 {
		trackOversteer = 1;
		trackLead = 0;
		maneuvrability = 5;
		CraterEffects = "BombCrater";
		explosionEffects = "BombExplosion";
		airLock = 0;
		irLock = 1;
		laserLock = 0;
		maxSpeed = 800;
	};

	class SAC_KAB500 : SAC_FAB250 {
		hit = 7500;
		indirectHit = 1600;
		indirectHitRange = 18;
		model = "\SACSu33\SACKAB500.p3d";
		proxyShape = "\SACSu33\SACKAB500_proxy.p3d";
		trackOversteer = 1;
		trackLead = 0;
		maneuvrability = 25;
		CraterEffects = "BombCrater";
		explosionEffects = "BombExplosion";
		airLock = 0;
		irLock = 1;
		laserLock = 1;
	};
};
*/
