// Generated by unRap v1.06 by Kegetys
/*
class CfgCloudlets {
	access = 0;
	class Default;	// External class reference

	class SACMissile1 : Default {
		interval = 0.001;
		circleRadius = 0;
		circleVelocity[] = {0, 0, 0};
		angleVar = 1;
		particleFSLoop = 0;
		particleShape = "\ca\Data\ParticleEffects\Universal\Universal";
		particleFSNtieth = 16;
		particleFSIndex = 12;
		particleFSFrameCount = 2;
		animationName = "";
		particleType = "Billboard";
		timerPeriod = 1;
		lifeTime = 8;
		moveVelocity[] = {0, 0, 0};
		rotationVelocity = 1;
		weight = 1;
		volume = 0.8;
		rubbing = 0.5;
		size[] = {0.5, 30};
		color[] = {{0.9, 0.9, 0.9, 0.9}, {0.9, 0.9, 0.9, 0.4}, {1, 1, 1, 0}};
		animationSpeed[] = {1};
		randomDirectionPeriod = 0.1;
		randomDirectionIntensity = 0.1;
		onTimerScript = "";
		beforeDestroyScript = "";
		lifeTimeVar = 2;
		positionVar[] = {0.3, 0.3, 0.3};
		MoveVelocityVar[] = {0.4, 0.4, 0.4};
		rotationVelocityVar = 1;
		sizeVar = 0.5;
		colorVar[] = {0, 0, 0, 0};
		randomDirectionPeriodVar = 0;
		randomDirectionIntensityVar = 0;
	};
};
*/
