// Generated by unRap v1.06 by Kegetys
/*
class CfgMagazines {
	class VehicleMagazine;	// External class reference
	class 180Rnd_30mm_GSh301;	// External class reference

	class SAC_150Rnd_30mm_GSh301 : 180Rnd_30mm_GSh301 {
		scope = 2;
		ammo = "SAC_B_30mm_HE";
		count = 150;
	};

	class SAC_80Rnd_S8T : VehicleMagazine {
		scope = 2;
		displayName = $STR_MN_S8T;
		ammo = SAC_R_S8T_AT;
		count = 80;
		initSpeed = 0;
	};

	class SAC_40Rnd_S8T : SAC_80Rnd_S8T {
		count = 40;
	};

	class SAC_80Rnd_S8T_HE : VehicleMagazine {
		scope = 2;
		displayName = $STR_MN_S8T;
		ammo = SAC_R_S8T_HE;
		count = 80;
		initSpeed = 0;
	};

	class SAC_6Rnd_R73 : VehicleMagazine {
		scope = 2;
		displayName = $STR_DN_R73;
		count = 6;
		ammo = SAC_M_R73_AA;
		initSpeed = 0;
	};

	class SAC_4Rnd_R73 : SAC_6Rnd_R73 {
		count = 4;
	};

	class SAC_6Rnd_R27RE : SAC_6Rnd_R73 {
		scope = 2;
		displayName = "R-27RE";
		count = 6;
		ammo = SAC_M_R27RE;
		initSpeed = 0;
	};

	class SAC_4Rnd_R27RE : SAC_6Rnd_R27RE {
		count = 4;
	};

	class SAC_6Rnd_R77 : VehicleMagazine {
		scope = 2;
		displayName = "R-77";
		count = 6;
		ammo = SAC_M_R77;
		initSpeed = 0;
	};

	class SAC_4Rnd_R77 : SAC_6Rnd_R77 {
		count = 4;
	};
	class 2Rnd_FAB_250;	// External class reference

	class SAC_24Rnd_FAB250 : 2Rnd_FAB_250 {
		scope = 2;
		ammo = SAC_FAB250;
		count = 24;
	};

	class SAC_6Rnd_KAB500 : SAC_24Rnd_FAB250 {
		displayName = "KAB-500";
		ammo = SAC_KAB500;
		count = 6;
	};
};
*/
