// Generated by unRap v1.06 by Kegetys
class CfgPatches {
	class Su33_Protatype_PT{
		units[] = {
			"Su33_Protatype_PT"
		};
		weapons[] = {};
		requiredVersion = 0.0.1;
		requiredAddons[] = {};
	};
};
