// Generated by unRap v1.06 by Kegetys
/*
class CfgWeapons {
	class GSh301;	// External class reference

	class SACGSh301 : GSh301 {
		scope = 2;
		displayName = "$STR_DN_GSh301";
		nameSound = "";
		dispersion = 0.01;
		initspeed = 860;
		reloadTime = 0.055;
		autoFire = 1;
		multiplier = 1;
		burst = 10;
		soundContinuous = 1;
		magazines[] = {"SAC_150Rnd_30mm_GSh301"};
		canLock = 2;
		cursoraim = "Vehicle_Grenade_W";
	};
	class S8Launcher;	// External class reference

	class SACS8Launcher : S8Launcher {
		magazines[] = {"SAC_80Rnd_S8T", "SAC_40Rnd_S8T"};
		cursor = "Air_Dot";
		cursorSize = 1;
	};
	class R73Launcher;	// External class reference

	class SACR73Launcher : R73Launcher {
		magazines[] = {"SAC_6Rnd_R73", "SAC_4Rnd_R73"};
		cursor = "\ca\Weapons\Data\clear_empty";
	};

	class SACR27Launcher : SACR73Launcher {
		displayName = "R-27RE";
		magazines[] = {"SAC_6Rnd_R27RE", "SAC_4Rnd_R27RE"};
		reloadTime = 0.3;
	};

	class SACR77Launcher : SACR73Launcher {
		displayName = "R-77";
		magazines[] = {"SAC_6Rnd_R77", "SAC_4Rnd_R77"};
		reloadTime = 0.3;
	};
	class LauncherCore;	// External class reference

	class SACBombLauncher : LauncherCore {
		scope = 1;
		displayName = "FAB-250";
		magazines[] = {"SAC_24Rnd_FAB250"};
		reloadTime = 0.1;
		aiRateOfFire = 5.0;
		aiRateOfFireDistance = 900;
		minRange = 300;
		minRangeProbab = 0.1;
		midRange = 1500;
		midRangeProbab = 0.8;
		maxRange = 2500;
		maxRangeProbab = 0.1;
		canLock = 2;
		cursorAim = "\ca\Weapons\Data\clear_empty";
		cursor = "\ca\Weapons\Data\clear_empty";
	};

	class SACBomb2Launcher : SACBombLauncher {
		displayName = "KAB-500";
		magazines[] = {"SAC_6Rnd_KAB500"};
		cursorAim = "\ca\Weapons\Data\clear_empty";
		cursor = "\ca\Weapons\Data\clear_empty";
	};
};
*/
