// Generated by unRap v1.06 by Kegetys

class SACMissile1 {
	class Light1 {
		simulation = "light";
		type = "RocketLight";
		position[] = {0, 0, 0};
		intensity = 0.01;
		interval = 1;
		lifeTime = 1;
	};
	
	class SACMissile1 {
		simulation = "particles";
		type = "SACMissile1";
		position[] = {0, 0, 0};
		intensity = 1;
		interval = 1;
		lifeTime = 1;
	};
};
