// Generated by unRap v1.06 by Kegetys

class Extended_Fired_EventHandlers {
	class Aus_Su27FAMILY {
		Aus_Su30_fired = "If ((_this select 1) == ""Aus_GSh301"") then {(_this select 0) animate [""WeaponAmount1"", (_this select 0) ammo ""Aus_GSh301""];} else {If ((_this select 1) == ""Aus_S8Launcher"") then {(_this select 0) animate [""WeaponAmount2"", (_this select 0) ammo ""Aus_S8Launcher""];} else {_this execVM ""\aus_su30\scripts\fired.sqf"";};};";
	};
};
